import { UseFormValue } from ".";
export declare function min(val: UseFormValue, minVal: number): boolean;
export declare function max(val: UseFormValue, maxVal: number): boolean;
export declare function required(val: UseFormValue): boolean;
export declare function requiredTrue(val: UseFormValue): boolean;
export declare function equal(val: UseFormValue, comparedValue: UseFormValue): boolean;
export declare function email(val: UseFormValue): boolean;
export declare function minLength(val: UseFormValue, minLength: number): boolean;
export declare function maxLength(val: UseFormValue, maxLength: number): boolean;
export declare function pattern(val: UseFormValue, pattern: string | RegExp): boolean;
export declare function numeric(val: UseFormValue): boolean;
export declare function decimal(val: UseFormValue): boolean;
